# Generated by Django 4.0.5 on 2023-07-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalbelum', '0003_alter_companydata_aboriginal_peoples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_de_envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Paquete'), ('F', 'Flete')], max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_origen', models.CharField(max_length=5)),
                ('cp_destino', models.CharField(max_length=5)),
                ('alto', models.CharField(max_length=5)),
                ('ancho', models.CharField(max_length=100)),
                ('largo', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_de_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portalbelum.tipo_de_envio')),
            ],
        ),
    ]
